module.exports = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};


/*
module.exports = {
  someSidebar: {
    Docusaurus: ['doc1', 'doc2', 'doc3'],
    Features: ['mdx'],
  },
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};
*/